### PR TITLE
ExpenseLocationService swagger document is added

### PR DESCRIPTION
**Pull request by sumncc**

### CODE REVIEW

**Comment by jonikamelcher** [comment]
Hello @sumncc. Can you please give us a little more insight about this API. Has this completed the CPA review?

**Comment by sumncc** [comment]
> Hello @sumncc. Can you please give us a little more insight about this API. Has this completed the CPA review?

Hi @jonikamelcher , These API were reviewed by CPA team and mentored by Mark Talbot. Please advise if I need to mention it somewhere. Thanks

**Comment by jonikamelcher** [comment]
@sumncc Would you happen to have an ARCH ticket number handy? If you would prefer, you can email DL Concur_APITechnicalWriters <DL_5BA96883ECB2111D8C00004C@global.corp.sap> with the information. Thank you.

**Comment by sumncc** [comment]
> @sumncc Would you happen to have an ARCH ticket number handy? If you would prefer, you can email DL Concur_APITechnicalWriters [DL_5BA96883ECB2111D8C00004C@global.corp.sap](mailto:DL_5BA96883ECB2111D8C00004C@global.corp.sap) with the information. Thank you.

@jonikamelcher , I will check with my other team members on Monday., if they Know about the ARCH ticket. It has been more than two years since we wrote these API.  Thank you.

**Comment by sumncc** [comment]
> @sumncc Would you happen to have an ARCH ticket number handy? If you would prefer, you can email DL Concur_APITechnicalWriters [DL_5BA96883ECB2111D8C00004C@global.corp.sap](mailto:DL_5BA96883ECB2111D8C00004C@global.corp.sap) with the information. Thank you.

@jonikamelcher  The ARCH ticket link is https://jira.concur.com/browse/ARCH-101 .
Thanks for your help.

**Comment by jonikamelcher** [comment]
Closing due to inactivity.

**Pull request closed without merging**
