### PR TITLE
Expense Mileage Service API Documentation

### PR DESCRIPTION
**Pull request by khaseebk**
Expense Mileage Service API Documentation
Mileage Service Mark Down
Mileage Service Swagger

### CODE REVIEW

**Comment by jonikamelcher** [comment]
Hello @khaseebk. Can you please give us a little more insight about this API. Has this completed the CPA review?

**Comment by khaseebk** [comment]
> Hello @khaseebk. Can you please give us a little more insight about this API. Has this completed the CPA review?

Hi @jonikamelcher , I checked with my team. Mileage Service API's were reviewed in past  and our principal engineer Mark Talbot coordinated the reviewed process . Thanks

**Comment by jonikamelcher** [comment]
Hi @khaseebk. Fantastic. Could you please provide us with an ARCH ticket? Thanks.

**Comment by khaseebk** [comment]
> Hi @khaseebk. Fantastic. Could you please provide us with an ARCH ticket? Thanks.

Hi @jonikamelcher The ARCH ticket link is https://jira.concur.com/browse/ARCH-24 . Thanks

**Comment by jonikamelcher** [comment]
Hi @khaseebk. Unfortunately we cannot publish documentation for an API that has not been approved by the current API requirements. Please contact Alyson Nawossa for more information on how to have this API reviewed. Thank you.

**Comment by jonikamelcher** [comment]
Closing due to inactivity.

**Pull request closed without merging**
