### PR TITLE
Docs for new itinerary v4 API.

### PR DESCRIPTION
**Pull request by teaganstrayed**
Swagger and reference docs for new Itinerary v4 API.

### CODE REVIEW

**Comment by jonikamelcher** [comment]
Hi @cjadams13. To fully prepare these docs for EA, we also need a Markdown file with our completed Documentation template. Is this going to be submitted in another PR? Thank you.

**Comment by teaganstrayed** [comment]
> Hi @cjadams13. To fully prepare these docs for EA, we also need a Markdown file with our completed Documentation template. Is this going to be submitted in another PR? Thank you.

I just pushed a commit with that file attached. Thanks!

**Comment by jonikamelcher** [comment]
> > Hi @cjadams13. To fully prepare these docs for EA, we also need a Markdown file with our completed Documentation template. Is this going to be submitted in another PR? Thank you.
> 
> I just pushed a commit with that file attached. Thanks!

Perfect! You will see this merged through shortly. Please avoid making any additional changes while this is in review (or just shoot me an email and I will include them). I'll send you a link when the reviewed version is available for preview on the Developer Center. Thank you!

**Comment by teaganstrayed** [comment]
> > > Hi @cjadams13. To fully prepare these docs for EA, we also need a Markdown file with our completed Documentation template. Is this going to be submitted in another PR? Thank you.
> > 
> > 
> > I just pushed a commit with that file attached. Thanks!
> 
> Perfect! You will see this merged through shortly. Please avoid making any additional changes while this is in review (or just shoot me an email and I will include them). I'll send you a link when the reviewed version is available for preview on the Developer Center. Thank you!

I just pushed one last change to update the FAQ before I had a chance to see this message. That should be it from our end. Thank you @jonikamelcher!

**Comment by jonikamelcher** [comment]
:shipit:

**Pull request merged**
