### PR TITLE
List service v4

### PR DESCRIPTION
**Pull request by melissa-von-wald**
Swagger files for the List, List Item, and List Category V4 APIs.
For SAP Internal API Hub only

### CODE REVIEW

**Review by MarcBell-SAP — COMMENTED** [review]
Use SAP's API Designer to validate your API documentation in OAS format. This will help ensure compatibility with all publishing of APIs (API Hub and Concur's Developer Center and internal wikis).

This is part of our [CPA review process](https://wiki.concur.com/confluence/pages/viewpage.action?spaceKey=ASSC&title=Schedule+API+Review).

**Review by MarcBell-SAP — CHANGES_REQUESTED** [review]
api-list-v4.json and api-listitem-v4.json have errors in API Designer. Please fix them and re-check with API Designer.

api-list-v4.json errors:
image

api-listitem-v4.json errors:
image

**Review by MarcBell-SAP — APPROVED** [review]
All files pass SAP API Designer validation tests. Minor errors in the Swagger editor that are acceptable.

Ready to publish.

@melissa-von-wald

**Comment by jonikamelcher** [comment]
:shipit:

**Pull request merged**
