### PR TITLE
added ga event tracking to links on go-to-market page

### PR DESCRIPTION
**Pull request by merittrompeter**
tracking clicks on the downloads, views, etc. on the go-to-market page of DevCenter

### CODE REVIEW

**Comment by nicklathe** [comment]
Based on what I've seen regarding ga, this looks great. I'm going to give this a :shipit: on my end.

**Comment by nicklathe** [comment]
@howarddierking, do you want in on this?

**Comment by merittrompeter** [comment]
FYI: ga does have a chrome plugin that enables local testing; based on that test they do seem to be working

**Comment by howarddierking** [comment]
I'm good if you are both good 

sounds to me like a :shipit:

**Pull request merged**
