### PR TITLE
Refs to Travel-Profile User/Company Notifications must be removed

### PR DESCRIPTION
**Pull request by arturoduar**
The pages (and links to these pages) to be removed are:

https://developer.concur.com/api-reference/travel-profile/v1.notification-user-resource.html

https://developer.concur.com/api-reference/travel-profile/v1.notification-company-resource.html

Reference Concur Jira: https://jira.concur.com/browse/TRVPRF-714

### CODE REVIEW

**Comment by arturoduar** [comment]
Hi. Please review

**Comment by jonikamelcher** [comment]
@arturoduar Hi. Has this API been through the deprecation process? We unfortunately cannot remove the documentation until we have adequately notified our users that this will no longer be available.

**Comment by arturoduar** [comment]
Hi @jonikamelcher , the APIs have been disabled fro a while. They are not servicing any notifications.

**Comment by arturoduar** [comment]
Hi @jonikamelcher , please see my note above. It is safe to remove the references.

**Comment by arturoduar** [comment]
Hi again @jonikamelcher, is there any more infoirmation that you need? How do we move this forward?

**Comment by jonikamelcher** [comment]
@arturoduar We do not typically remove documentation from the Developer Center unless there is a security risk. All other documentation is deprecated. I will have to follow up with this but we currently have a priority item moving through our team. I will let you know when I have more information. Thank you.

**Comment by arturoduar** [comment]
Thank you, @jonikamelcher. If documentation can only be deprecated, how is that done? Do I need to present a different PR? Please let me know once you have the bandwidth.

**Comment by jonikamelcher** [comment]
Hi @arturoduar. Please contact Alyson Nawossa for more information about deprecating these APIs. It sounds like User is pretty disabled, but we are still seeing callers for Company. Alyson will be able to give you more information and help get you to a place where we can either, fully remove the documentation, or deprecate it. Thank you.

**Comment by arturoduar** [comment]
Hi @jonikamelcher. I sent an internal SAP email to Alyson, requesting advice. Thank you!

**Pull request closed without merging**
