### PR TITLE
Remove beta wordin

### PR DESCRIPTION
**Pull request by squarebing**
Removed the following code from profile-beta pages (company, user, gettingStarted)

```
{% include prerelease.html %}
```

### CODE REVIEW

**Comment by charlieconcur** [comment]
@squarebing -- We need to resolve the issues with the path as well -- it says `\/profile-beta` and we need to version the files. I'm going to close this pull request and open another with those changes.

@carolrussell Note this is shifting from pre-release to GA.

**Comment by carolrussell** [comment]
Hi.  This needs to finish the API Success Review and it needs to go through the launch process before it moves to GA.  It also needs review by the tech writers for formatting  as there are several pieces missing (such as scope, etc).  Thanks.

**Comment by charlieconcur** [comment]
As noted before, closing this issue.

**Comment by carolrussell** [comment]
Thank you Charlie.  I assume it's Bing working this one and if so, please have him reach out to me.  Assuming he can see these comments?  Thanks.  @squarebing @charlieconcur

**Comment by charlieconcur** [comment]
@squarebing can see these comments. All I am going to do is fixup the legacy (aka 'bad') way of naming paths (complete with redirects) and then it will be up to you (or your delegate) and Bing to work out what you want to have happen.

**Pull request closed without merging**
