### PR TITLE
UniqueID Type attribute ducumentation

### PR DESCRIPTION
**Pull request by LKnotek**
Document Type properly under the UniqueID element.
Add table describing all the possible Type values.

## Pull Request Checklist

**Complete and check all items that are applicable.**

- [x] Proofread documentation changes for spelling and grammatical errors
- [x] Used Markdown code blocks for all applicable examples using code
- [ ] Used relative links when linking to other documentation on Developer Center
- [ ] If creating new API reference pages, followed the guidelines stated [in the wiki](https://github.com/concur/developer.concur.com/wiki/Creating-API-Reference-pages)
- [ ] If moving pages, added [page redirects](https://github.com/concur/developer.concur.com/wiki/Adding-Redirects) so users are redirected to the new page

### CODE REVIEW

**Comment by charlieconcur** [comment]
@LKnotek Please have a team member peer review the change and give a thumbs up.

**Comment by LKnotek** [comment]
@charlieconcur I am not able to add any reviewer, can you please check my rights for this project?

**Comment by LKnotek** [comment]
@charlieconcur hi again, can you please check my comment above? This pull rq is opened for almost 2 months but I see no way how to add a reviewer there. Thank you.

**Comment by charlieconcur** [comment]
Merged. Next time, let's make sure we get the peer review done, even if it's a note from you saying [insert name here] reviewed and approved.

**Pull request merged**
