### PR TITLE
TVR-12960 Agency proposal via API v4 - Documentation proposal endpoint - Reference page

### PR DESCRIPTION
**Pull request by marcdalleau**
Hi team,
I want to provide the specification of the Request API v4 proposal endpoint into preview.developer.concur.com, so that Early Adopters of this feature can perform their developments with the necessary documentation.

### CODE REVIEW

**Comment by jonikamelcher** [comment]
Hi @marcdalleau. Temporarily, could you please relocate the schemas for the proposal endpoint to the proposal doc? This will allow us to have a unique link we can send out for EA without affecting any live materials. We will move the schemas back to the main page once we are ready for GA. Thank you!

**Comment by marcdalleau** [comment]
@jonikamelcher I made the change, please take a look

**Comment by marcdalleau** [comment]
> Hi @marcdalleau. Temporarily, could you please relocate the schemas for the proposal endpoint to the proposal doc? This will allow us to have a unique link we can send out for EA without affecting any live materials. We will move the schemas back to the main page once we are ready for GA. Thank you!

@jonikamelcher I made the change, please take a look

**Comment by jonikamelcher** [comment]
:shipit:

**Pull request merged**
