### PR TITLE
LEU, List and List Item V4 Preview.Developer.Concur Pages

### PR DESCRIPTION
**Pull request by sarah-williamson**
Pages for EA for V4 List and List Item. Need to have available by July 10 on preview.developer.com.

### CODE REVIEW

**Comment by jonikamelcher** [comment]
Hi @sarah-williamson. We will review this PR but cannot promise this will be completed by the July 10th date. We will reach out as soon as possible to let you know if we require anything additional to keep this moviing. Thank you.

**Comment by sarah-williamson** [comment]
@jonikamelcher Thanks for your help! Apologies for the tight turnaround. FYI - This is needed for a client (EY) deliverable. Please let me know when you have an estimated date.

**Comment by sarah-williamson** [comment]
I've added the page updates for Launch External URL as well. Please let me know if those changes are visible with this PR. It should be for the Launch External URL page and the Launch External URL Request page, under Callouts. I'm assuming no Swagger files are needed because we don't have them currently on developer.concur. The API itself is internal. In case they are needed, we can use the QA and SEA-Prod from here: https://wiki.concur.com/confluence/display/EENG/LEU+Server+Environment+List

**Comment by jonikamelcher** [comment]
Hi @sarah-williamson. All v4 APIs require Swagger, as per SAP. If you could go ahead and add the Swagger file as well for LEU, we would appreciate it. As a heads up, you will likely see this PR merged through after the Swagger file is added and we'll begin our review. We will reach out to you via email with any updates or questions after this is merged.

**Comment by sarah-williamson** [comment]
@jonikamelcher I've added a Swagger file for LEU. Please let me know if anything else is needed. I went ahead and used the Swagger file for our Seattle Prod environment https://launchexternalurl-prod.seapr1.uscom.cnqr.delivery/swagger-ui.html#/Launch_External_URL_API.  We do have Swaggers for other environments if those are needed, per https://wiki.concur.com/confluence/display/EENG/LEU+Server+Environment+List.

**Comment by sarah-williamson** [comment]
@jonikamelcher Do you have an idea of when we will be able to have this content on the preview site and/or when this PR will be reviewed? I'm trying to understand when we will be able to provide the link to our customer.

**Comment by jonikamelcher** [comment]
@sarah-williamson I unfortunately can't give you a super accurate timeline right now because we won't have the ability to look further into this until the end of this week. Optimistically I would hope these would be ready to publish by the end of next week but that is dependent on any questions we have along the way. Just from a cursory glance I can let you know we will need code samples for the endpoints, both request and response, so if you have the ability to include these, this will speed up the process next week. Thank you.

**Comment by sarah-williamson** [comment]
@jonikamelcher Thanks for the support. Do you need code samples for the Lists, List Items, Launch External URL, or all three?

**Comment by jonikamelcher** [comment]
@sarah-williamson All three as it is displayed in the documentation template. Each endpoint needs a request and response code sample.

**Comment by sarah-williamson** [comment]
@jonikamelcher We have sample request/responses for the Launch External URL here: https://github.concur.com/expense-external-services/launch-external-url-service/blob/develop/docs/leuconfig.md.

**Comment by sarah-williamson** [comment]
FYI - we're working on getting the sample request/responses for Lists and List Items.

**Comment by sarah-williamson** [comment]
After Melissa's update, we should have the request and responses now. Please let me know if there is anything else needed.

**Comment by jonikamelcher** [comment]
Hi @sarah-williamson. We are going to go ahead and merge this through to start our review while we wait on some additional material for another API that's in the launch process. Please do not make any further changes to the files while we are reviewing (or just shoot us an email and we'll be happy to make any changes for you). If we have any questions, we'll shoot you an email ASAP. Thank you.

**Comment by sarah-williamson** [comment]
Great! Thanks so much!

**Pull request merged**
