### PR TITLE
change tracking names to file names

### PR DESCRIPTION
**Pull request by merittrompeter**
updating GA tracking to desired format

### CODE REVIEW

**Comment by henryyamamoto-concur** [comment]
I think this is pretty safe, but I'm not a doctor. @nicklathe

**Comment by nicklathe** [comment]
Looks good. It looks like this is just getting more granular on what exactly was clicked/viewed/whatever?

**Comment by merittrompeter** [comment]
Absolutely, instead of the generic titles I had in before, we're substituting the file names of the files.

**Comment by nicklathe** [comment]
Cool. :shipit:

**Pull request merged**
