### PR TITLE
Update ConnectionRequests.markdown

### PR DESCRIPTION
**Pull request by jimandersen**
Placeholders inserted for XML Examples of successful responses for the following: 

	• GET Common connection requests
		○ Need a valid supplier ID
	• PUT common connections - create a connection on behalf of the specified user
		○ Need valid Supplier ID
	• DELETE common connection
		○ Need a valid specified resource to complete the process
	• GET Common connection requests by ID
		○ Need a resource with the specified ID
	• PUT Common connection requests by ID
		○ The schema is incorrectly configured because the data at the root level is invalid. Need a valid object ID

### CODE REVIEW

**Comment by henryyamamoto-concur** [comment]
@jimandersen Are you cutting and replacing all the text? The only reason I ask is that I'm not seeing the diffs from what was there originally.

**Comment by jimandersen** [comment]
Then I must be doing something wrong in GitHub because I'm building the pages using .md directly.

**Comment by henryyamamoto-concur** [comment]
Wrong page. Should be the same page in api-reference.

**Comment by henryyamamoto-concur** [comment]
Wrong page. Should be the same page in api-reference.

**Pull request closed without merging**
