### PR TITLE
hotel-servce-2 fixes

### PR DESCRIPTION
**Pull request by henry-yang-sap**

### CODE REVIEW

**Comment by sarraloew** [comment]
Hi Henry, the PenaltyDescription table in the Availability page is broken. Please change that table heading to:
#### <a name="penalty-description"></a>PenaltyDescription
|Name|Type|Description|
|---------|----------|-----------------------|

**Comment by sarraloew** [comment]
Hi Henry, there is a fix to a table in Availability.markdown that you don't have in your repo fork. Please pull the latest to get that fix included.

**Comment by henry-yang-sap** [comment]
> Hi Henry, there is a fix to a table in Availability.markdown that you don't have in your repo fork. Please pull the latest to get that fix included.

I've merged from preview and fixed another malformed table.

**Comment by sarraloew** [comment]
Looks good, thanks Henry!

**Comment by sarraloew** [comment]
:shipit:

**Pull request merged**
