### PR TITLE
identity.v4.json - fixed errors

### PR DESCRIPTION
**Pull request by suhita-banerjee**
https://jira.concur.com/browse/CP-3315

### CODE REVIEW

**Review by MarcBell-SAP — CHANGES_REQUESTED** [review]
Please change the name of this file to Identity.v4.json

**Review by MarcBell-SAP — COMMENTED** [review]
Please try this in API Designer and make the required corrections. @suhita-banerjee

**Comment by suhita-banerjee** [comment]
The errors have been fixed. I've uploaded the latest file with no errors.

**Comment by MarcBell-SAP** [comment]
:shipit:

**Pull request merged**
