### PR TITLE
Name field is required when Creating Report

### PR DESCRIPTION
**Pull request by HNozakiC**
Name field is required when Creating Report

### CODE REVIEW

**Comment by charlieconcur** [comment]
:shipit:

**Comment by sarraloew** [comment]
@HNozakiC Is this a change to the existing functionality, or a documentation correction? If this is a change, we need to announce it using a release note to make sure the API users know.

**Comment by jonikamelcher** [comment]
@HNozakiC Is this a change to the existing functionality, or a documentation correction? If this is a change, we need to announce it using a release note to make sure the API users know.

**Comment by HNozakiC** [comment]
Sorry for making confusion. It is a documentation correction request. Functionally, Name field is already required.

**Comment by jonikamelcher** [comment]
:shipit:

**Pull request merged**
