### PR TITLE
Updated Logo Guidelines Section Formatting

### PR DESCRIPTION
**Pull request by LaurelC3**
Removed the checkmarks and some text for a cleaner look.

### CODE REVIEW

**Review by RoAnnC1 — CHANGES_REQUESTED** [review]
Laurel,
Now that there's no checkmark can we update so the text isn't centered in the first column? It looks odd and is harder to read that way.

**Comment by LaurelC3** [comment]
Yes – absolutely. Feel free to re-format however looks cleanest!

**Comment by RoAnnC1** [comment]
I don't have permission to change your pull request. All you need to do is remove the colon from this line. That's what makes the text centered.
:---:|---

Instead it should be
---|---

**Comment by LaurelC3** [comment]
I'll create a new pull request with correct formatting to remove centered text.

**Pull request closed without merging**
