### PR TITLE
Update launch-external-url-v4-request.markdown

### PR DESCRIPTION
**Pull request by sarah-williamson**
Added lang code parameter per EIS-1459

### CODE REVIEW

**Comment by RoAnnC1** [comment]
:shipit:

**Comment by sarah-williamson** [comment]
Hi Tech Pubs - I just found out we have one outstanding question on one edit. Can you hold off on this change for now (I expect an update by EOD today)?

**Comment by jonikamelcher** [comment]
@sarah-williamson Absolutely. Just let us know when this is set to merge. Thank you!

**Comment by sarah-williamson** [comment]
@jonikamelcher Thanks!

**Comment by sarah-williamson** [comment]
@jonikamelcher FYI - I've made the updates, so it is ready to go now.

**Pull request merged**
