### PR TITLE
Added description to ClientLocator

### PR DESCRIPTION
**Pull request by RoAnnC1**
Fixed some code element formatting

### CODE REVIEW

**Comment by sarraloew** [comment]
:shipit:

**Comment by RoAnnC1** [comment]
@charlieconcur 
Can you confirm the nesting looks okay in the support doc? It looks fine on preview. For some reason the numbered list was one long list. Carol wants this updated this week.

**Comment by charlieconcur** [comment]
@RoAnnC1 Do you want it to be a numbered list?

**Comment by charlieconcur** [comment]
I will merge and we can adjust separately if desired.

**Pull request merged**
