### PR TITLE
Creating new BETA user locations API reference page

### PR DESCRIPTION
**Pull request by brittnwestSAP**
This requires peer review by the Locate team before publish

This is a BETA reference so will not be added to the navigation at this time.

## Pull Request Checklist

**Complete and check all items that are applicable.**

- [x] Proofread documentation changes for spelling and grammatical errors
- [x] Used Markdown code blocks for all applicable examples using code
- [x] Used relative links when linking to other documentation on Developer Center
- [x] If creating new API reference pages, followed the guidelines stated [in the wiki](https://github.com/concur/developer.concur.com/wiki/Creating-API-Reference-pages)
- [ ] If moving pages, added [page redirects](https://github.com/concur/developer.concur.com/wiki/Adding-Redirects) so users are redirected to the new page

### CODE REVIEW

**Comment by brittnwestSAP** [comment]
@rseera

**Comment by brittnwestSAP** [comment]
@charlieconcur are there additional access rights @KetanShrikhande needs to push changes to this PR? He is also reviewing from the Locate team.

**Comment by charlieconcur** [comment]
This is on external GitHub which is a different user than Enterprise -- so requires github.com credentials.

**Comment by brittnwestSAP** [comment]
Yes @KetanShrikhande is his public github account. @KetanShrikhande I can't tell from your profile if you are a part of the Concur organization on public. Will send a separate email to get you set up if not.

**Comment by charlieconcur** [comment]
I think that because this is a patch (rather than a fork) nobody else can push changes but you, @brittnwestSAP -- but I'm not 100% sure that's for real true.

**Comment by brittnwestSAP** [comment]
Ah ok thanks. Will get the changes from Ketan and incorporate.

**Comment by KetanShrikhande** [comment]
Hello @charlieconcur  @brittnwestSAP  - If the patch can be merged then I can fork and raise a PR separately. Its just that the changes from patch-10 are not in the preview branch that I need to push to patch-10

**Comment by charlieconcur** [comment]
Merged.

**Pull request merged**
