### PR TITLE
Code of conduct addition

### PR DESCRIPTION
**Pull request by charlieconcur**
We will need to edit the email address as appropriate. Hopefully @sarraloew already has an externally available tech pubs DL we can use.

### CODE REVIEW

**Comment by sarraloew** [comment]
This looks like it applies to the forum- who is responsible for moderating that?

**Comment by charlieconcur** [comment]
It applies to both, actually. I think Doug owns the forum.

**Comment by charlieconcur** [comment]
@sarraloew Do you want to move this pull request forward?

**Comment by charlieconcur** [comment]
Closing as there doesn't appear to be any support for this -- unfortunate, but a reality.

**Pull request closed without merging**
