### PR TITLE
Add sidebar menu for Budget's API Explorer page

### PR DESCRIPTION
**Pull request by elankumaranrk**
Add sidebar menu for Budget's - Swagger API Explorer page.

### CODE REVIEW

**Review by charlieconcur — CHANGES_REQUESTED** [review]
We need to add {% include prerelease.html %} to the top of the Swagger since this is pre-release.

**Comment by charlieconcur** [comment]
I will also note Budget v4 isn't in the navigation for the HTML documentation.

**Comment by charlieconcur** [comment]
@jtbigwoo and @carolrussell and @sarraloew Please take a look -- are we adding pre-release documentation to sidebars now?

**Comment by elankumaranrk** [comment]
@charlieconcur probably not. I included the navigations merely based on your previous note and I will revert it if it shouldn't be added.

**Comment by sarraloew** [comment]
We won't add this to the nav until GA.

**Comment by charlieconcur** [comment]
Thanks, @sarraloew.

@elankumaranrk Remove all references to the docs from the sidebars _and_ keep the pre-release notification at the top of the Swagger.

**Review by charlieconcur — APPROVED** [review]

**Comment by charlieconcur** [comment]
:shipit:

**Comment by sarraloew** [comment]
:shipit:

**Pull request merged**
