### PR TITLE
Remove pre-release status from Hotel Service 2

### PR DESCRIPTION
**Pull request by LKnotek**
Removing prerelease.html from all HS2 pages on PM request as development has been finished some time ago with first partners being live and other migrating / waiting for onboarding.

### CODE REVIEW

**Comment by charlieconcur** [comment]
:shipit:

**Comment by sarraloew** [comment]
This documentation is incomplete, so it cannot go GA. I'll reach out to the PM to get the missing information.

**Comment by LKnotek** [comment]
Hi @sarraloew can you please let us know what are you missing there so we can have the change merged? I was checking with PMs interested in this change but no one from them has received any info so far. Thank you very much!

**Comment by LKnotek** [comment]
@sarraloew, @jonikamelcher thank you for the review, we've finished changes based on your notes (sent via email) - can you please take a look and let us know if anything else is missing / incomplete?

**Comment by charlieconcur** [comment]
@sarraloew Believe this is waiting on your review.

**Comment by sarraloew** [comment]
Pending an answer, email sent to dev 4/23.

**Comment by sarraloew** [comment]
Resolved, ready to merge. :shipit:

**Pull request merged**
