### PR TITLE
ERS-3368: Update Reports.swagger.json

### PR DESCRIPTION
**Pull request by rajatkasliwal**
Latest swagger changes for Expense Report Service (ERS)

**We have added** 

- **New query string parameters**: 'includeAllComments', 'includeItemizations'
- **New Properties**: 'parentExpenseId', 'employeeId', 'isAuditorComment', 'expenseId', 'defaultFieldAccess', 'employee'

### CODE REVIEW

**Comment by rajatkasliwal** [comment]
Hello @jonikamelcher .... please take a look and merge. Thank you!

**Comment by jonikamelcher** [comment]
Hi @rajatkasliwal. We are no longer accepting changes to this repository. The site is currently in freeze until the end of the month. We will release instructions for the new repo when it is fully prepared. Thank you.

**Comment by rajatkasliwal** [comment]
Hello @jonikamelcher ..... Did the freeze end ? any update on the new repo ? Thank You

**Comment by rajatkasliwal** [comment]
Thanks @jonikamelcher ..... will wait till end of the week for more updates.

**Pull request closed without merging**
