### PR TITLE
NV-35142: Docs - Modify API for Get Payments endpoint to include new optional field

### PR DESCRIPTION
**Pull request by prithvi-varla**

### CODE REVIEW

**Comment by prithvi-varla** [comment]
@ANawossa , as discussed i created the pull req only for the existing api. can you approve this. Thanks

**Comment by jonikamelcher** [comment]
@prithvi-varla Changes look great. Quick question, has the Swagger file been updated as well?

**Comment by prithvi-varla** [comment]
@jonikamelcher , Yes, the code change covers the swagger changes aswell.

**Comment by prithvi-varla** [comment]
@jonikamelcher, can you merge it for us to test in preview.

**Comment by jonikamelcher** [comment]
@prithvi-varla I unfortunately have to wait for an unrelated doc to clear before I can make another push. Thanks for your patience. I am hoping I will be able to do so before EOD.

**Comment by jonikamelcher** [comment]
@prithvi-varla Follow-up: We will need an updated Swagger file as well. Because this is a living document that is already in our navigation, any changes to the Preview site will automatically be transferred to the Livesite when we push to Live next (this usually happens once a day). Is this ready to be consumed by the public?

**Comment by prithvi-varla** [comment]
@jonikamelcher , this is the swagger url to this endpoint. Yes it is ready in production to be used by customers.
https://invoice-payment-metadata.nonprod.cnqr.tech/swagger-ui.html#/Resources/manyUsingGET

**Comment by jonikamelcher** [comment]
@prithvi-varla Great. Please update the api-explorer/v4-0/InvoicePay.swagger2.json file with the most current Swagger and I will get this merged for you!

**Comment by jonikamelcher** [comment]
:shipit:

**Pull request merged**
