### PR TITLE
Clean-up of documentation before GA

### PR DESCRIPTION
**Pull request by vbimba**
Cleaned up:
- Fixed previous formatting issues
- Error handling
- Availability elements
- Reservation elements
- Search elements
- Added v-payment section

### CODE REVIEW

**Comment by charlieconcur** [comment]
@vbimba Please let us know when you are finished with your commits and ready for us to review / merge.

**Comment by charlieconcur** [comment]
It would also be helpful to provide a more meaningful title. ;)

**Comment by vbimba** [comment]
@charlieconcur Thanks. I changed the title. You can move forward.

Thanks,
Vai

**Comment by charlieconcur** [comment]
I'm going to go ahead and merge this pull request noting it has (apparently) been in pre-release given the title YET it's been around for a long time. I would like to see us clean up the paths as well as the Markdown at some point in the future.

@sarraloew and @RoAnnC1 for visibility.

**Pull request merged**
