### PR TITLE
Adding PDFs

### PR DESCRIPTION
**Pull request by RoAnnC1**
Charlie,
We need URLs to put in a document that partners will be using. These docs are currently only available once you log in to Concur and need to be visible before that. They will not be in the TOC.

### CODE REVIEW

**Comment by charlieconcur** [comment]
Things to resolve...

No spaces in file name.
File name in all lower case.
Need to be in something other than the root path. Based on the file name / purposes perhaps under /manage-apps.

I'm going to assume these have to stay in PDF format?

**Comment by charlieconcur** [comment]
I found this already in place with a newer revision date...

https://github.com/concur/developer.concur.com/blob/preview/src/manage-apps/go-market-docs/app-center-letter-of-authorization.pdf

...which also begs the question if these should be in the `/manage-apps/go-market-docs/` path.

**Comment by RoAnnC1** [comment]
Didn't realize the LOA was the link auth doc. I'll remove it.

**Review by sarraloew — APPROVED** [review]

**Comment by sarraloew** [comment]
Looks good. We will be referencing this file on an ongoing basis, not just when partners go to market, so I think this location is a good fit for it. The PDFs are required so that no one can change the legal text. 
:shipit:

**Pull request merged**
