### PR TITLE
ERS-2262 - Review draft for Reports V4 API documentation [do not merge]

### PR DESCRIPTION
**Pull request by greg-grove-sap**

### CODE REVIEW

**Comment by jonikamelcher** [comment]
Hi Greg, can you please provide us a little more information on this PR? I see you have this noted as a do not merge, but I also see you have added this to the navigation, which is likely to create conflicts later on. A writer will add the API to the navigation once a full review has been completed. Could you please give us a little insight? Thank you.

**Comment by greg-grove-sap** [comment]
Hi @jonikamelcher - This PR was meant to kickstart a conversation with documentation team for adding Reports V4 to the developer portal.  Is there an appropriate resource that we can work with to walk through formulation of a proper PR?

**Comment by jonikamelcher** [comment]
@greg-grove-sap In the future, if you could please send an email to DL Concur_APITechnicalWriters <DL_5BA96883ECB2111D8C00004C@global.corp.sap> requesting a review, that would be great. This makes sure all the writers are notified. In the meanwhile, please remove this from the navigation and I will pass this information along to the team. Thank you.

**Comment by greg-grove-sap** [comment]
@jonikamelcher Done.  Please let me know who our point of contact should be in getting this reviewed.

**Pull request merged**
