### PR TITLE
Updating user provisioning documentation. 

### PR DESCRIPTION
**Pull request by mvahlsing98117**
Made some updates to the user provisioning documentation in preparation for customer viewing and integration with SAP projects. 
The latest swagger needs to be pulled in as well. 

Thanks

### CODE REVIEW

**Comment by mvahlsing98117** [comment]
Making updates to the use provisioning documentation. Want to verify that the updates fit within Tech Hub's publishing guidelines.

**Comment by jonikamelcher** [comment]
Hi @mvahlsing98117. We need this documentation broken out a little further. Each PUT, POST, PATCH, is a separate action and thus needs it's own section of the documentation template. We cannot have all the actions under one portion because it tends to cause confusion. If you could please break these out into their own Create a resource/Endpoint Documentation portion of the template, we can complete the review. It would also be helpful to know in what situations each would be used (Is POST like a create? PUT an edit? PATCH...) Thank you.

**Comment by mvahlsing98117** [comment]
Made some changes based on the suggestions above. Thanks for the input and let me know if more changes are needed.

**Comment by jonikamelcher** [comment]
Hi @mvahlsing98117. Looking great! I will take a deeper look into this early next week and get it merged through. Thank you!

**Comment by jonikamelcher** [comment]
Hi @mvahlsing98117. I'll be merging this through shortly and then adding some formatting changes in the next couple days, so if you see the page change a little bit, it is expected. Thank you!

**Pull request merged**
