### PR TITLE
Archiving App Center release notes to yearly

### PR DESCRIPTION
**Pull request by charlieconcur**
Combines all of the legacy App Center release notes as follows.

> Note: .markdown files become .html when merged and published.

New Resource|Combines & Deletes
---|---
/tools-support/release-notes/sap-concur-app-center/2017.markdown|app-center-2017-01-01.pdf<br>app-center-2017-02-01.pdf<br>app-center-2017-05-01.pdf<br>app-center-2017-07-01.pdf<br>app-center-2017-08-01.pdf<br>app-center-2017-09-01.pdf<br>app-center-2017-10-01.pdf<br>app-center-2017-12-01.pdf
/tools-support/release-notes/sap-concur-app-center/2016.markdown|app-center-2016-01-01.pdf<br>app-center-2016-02-01.pdf<br>app-center-2016-03-01.pdf<br>app-center-2016-05-01.pdf<br>app-center-2016-06-01.pdf<br>app-center-2016-07-01.pdf<br>app-center-2016-08-01.pdf<br>app-center-2016-09-01.pdf<br>app-center-2016-10-01.pdf<br>app-center-2016-11-01.pdf<br>app-center-2016-12-01.pdf
/tools-support/release-notes/sap-concur-app-center/2015.markdown|app-center-2015-02-13.pdf<br>app-center-2015-02-27.pdf<br>app-center-2015-03-13.pdf<br>app-center-2015-03-27.pdf<br>app-center-2015-05-01.pdf<br>app-center-2015-07-01.pdf<br>app-center-2015-09-01.pdf<br>app-center-2015-10-01.pdf<br>app-center-2015-12-01.pdf
/tools-support/release-notes/sap-concur-app-center/2014.markdown|app-center-2014-05-01.pdf<br>app-center-2014-06-01.pdf<br>app-center-2014-07-01.pdf<br>app-center-2014-08-01.pdf<br>app-center-2014-09-01.pdf<br>app-center-2014-10-10.pdf<br>app-center-2014-11-14.pdf<br>app-center-2014-12-12.pdf

You will also note the archive for 2018 has also been created which incorporates these resources:

New Resource|Combines & Deletes (in 2019)
---|---
/tools-support/release-notes/sap-concur-app-center/2018.markdown|app-center-2018-02-01.pdf<br>app-center-2018-05-14.markdown<br>app-center-2018-06-01.markdown<br>app-center-2018-07-10.markdown<br>app-center-2018-08-18.markdown<br>app-center-2018-09-04.markdown<br>app-center-2018-10-19.md

Some outstanding questions:

**Do we move these to their own `/appcenter` path as a peer to `api`...?** My vote is yes, and now is the time to do so - we will be breaking links by deleting the original PDF files, which we cannot redirect anyway. Note: We can redirect any `.markdown` files, not that I advocate spending the time to do so. The pull request now reflects moving App Center release notes to their own path.

**Do we forego individual release files and stick with annual files from the very start?** My vote is also yes, given the amount of churn (not much) and these aren't press releases.

### CODE REVIEW

**Comment by sarraloew** [comment]
I agree with moving the app center RNs to their own location, a peer of api. I don't see that change reflected in the index.markdown page changes. 
I think it makes sense to consolidate them into yearly pages.

**Comment by charlieconcur** [comment]
@LaurelC3 Would you like to form an opinion?

**Comment by LaurelC3** [comment]
Hi @charlieconcur apologies for the delay. I'm ok with moving these -- I think we only have a few documents that point to them, so I'll just need to re-link. 

RE: annual release notes, I agree that having all of the release notes on one page does make things cleaner, especially if we have apps that are in the "coming soon" category for a while. However, I think we should make sure we include the month/release date that the app was live as it helps clients see what's new. The release notes are important to clients so they can review and promote/disable user apps as needed. Including the release date would help them see what's been launched in the App Center since they last reviewed.

**Comment by sarraloew** [comment]
We can add the release date to the header for each month, that makes sense.

**Comment by LaurelC3** [comment]
If we'll still have each monthly release separated or noted within the annual files, I don't think we need to add the specific date. As long as you'd be able to see that, for example, Voll went live in the September 2018 release, it's fine and we can go ahead and make this change.

**Comment by sarraloew** [comment]
Ok, sounds like the current format is good to go. Once this change is merged, I can add the Dec Draft App Center RNs. 
:shipit:

**Comment by charlieconcur** [comment]
@sarraloew Note the changes in the paths above -- instead of having a lot of duplication...

```
/tools-support/release-notes/sap-concur-app-center/sap-concur-app-center-2017.markdown
```

...it is now simplified...

```
/tools-support/release-notes/sap-concur-app-center/2017.markdown
```

**Pull request closed without merging**
