### PR TITLE
Update payment-batches.markdown

### PR DESCRIPTION
**Pull request by dstaab**
## Pull Request Checklist

**Complete and check all items that are applicable.**

- [ ] Proofread documentation changes for spelling and grammatical errors
- [ ] Used Markdown code blocks for all applicable examples using code
- [ ] Used relative links when linking to other documentation on Developer Center
- [ ] If creating new API reference pages, followed the guidelines stated [in the wiki](https://github.com/concur/developer.concur.com/wiki/Creating-API-Reference-pages)
- [ ] If moving pages, added [page redirects](https://github.com/concur/developer.concur.com/wiki/Adding-Redirects) so users are redirected to the new page

### CODE REVIEW

**Comment by dstaab** [comment]
We are making the following changes because we found that these 2 minor adjustments are required in order to get an actual file download.  Without these adjustments, the Partner or Customer developer only close the batch & no file link is available.

-     POST /expense/paymentbatch/v1.2/batch/{BatchID}/closed
+    POST /expense/paymentbatch/v1.1/batch/{BatchID}/close

**Comment by dstaab** [comment]
Charlie - 
The wiki page below provides the agile teams.  If you search "extract" by using Ctrl F,  Parastoo & Teresa Kearney come up as the Scrum Master and Product Owner, respectively. https://wiki.concur.com/confluence/pages/viewpage.action?title=Agile+Teams&spaceKey=EENG
Neither of them are coming up as Github users.  I will copy you on the email.

**Comment by dstaab** [comment]
The edits submitted are accurate based on my team's use of the APIs

**Comment by charlieconcur** [comment]
I'm going to close this pull request because it's way out of date with the balance of the branch. Let's open up a new one.

**Pull request closed without merging**
