### PR TITLE
Add receipts v4 swagger

### PR DESCRIPTION
**Pull request by cfreiner**
This adds a Swagger 2 spec for Receipts v4. The API is already GA and has been documented on Dev Center [here](https://developer.concur.com/api-reference/receipts/get-started.html), but has never had a Swagger page. Thanks in advance for any feedback!

### CODE REVIEW

**Comment by jonikamelcher** [comment]
Hi @cfreiner. If you could please run this through the [SAP API Designer](https://help.sap.com/viewer/e63fe47de8f84a68b618ed689af9a28b/Cloud/en-US/186d9d5f72694954a52a5fa4c56fe5f2.html) and [Swagger.io](https://editor.swagger.io/) validation tools, this will allow us to submit to the SAP API Hub. Unfortunately if either of the validation tools throws an error, SAP will not allow us to publish. Thank you.

**Comment by cfreiner** [comment]
> Hi @cfreiner. If you could please run this through the [SAP API Designer](https://help.sap.com/viewer/e63fe47de8f84a68b618ed689af9a28b/Cloud/en-US/186d9d5f72694954a52a5fa4c56fe5f2.html) and [Swagger.io](https://editor.swagger.io/) validation tools, this will allow us to submit to the SAP API Hub. Unfortunately if either of the validation tools throws an error, SAP will not allow us to publish. Thank you.

Sure thing. Is there a separate set of steps for SAP engineers to access the SAP API Designer?

**Comment by jonikamelcher** [comment]
@cfreiner Not that I am aware of. These were the only instructions for accessing that we were given.

**Comment by jonikamelcher** [comment]
:shipit:

**Pull request merged**
