### PR TITLE
Update the example of Password update

### PR DESCRIPTION
**Pull request by shinyay-jptc**
Not able to update the password by using current example as below.

But the request actually succeeds if we use "user" tab instead of "userprofile".

### CODE REVIEW

**Comment by charlieconcur** [comment]
Please have a peer review done.

**Comment by charlieconcur** [comment]
@bing-hu-concur Please take a look.

**Comment by charlieconcur** [comment]
Ping @bing-hu-concur.

**Comment by squarebing** [comment]
Bing Hu [4:26 PM]
have you verified the PR is correct?

Shinya Yoshimura [4:41 PM]
We Concur Japan team tested before submit PR.

**Comment by squarebing** [comment]
Based on Shinya Yoshimura's confirmation, please approve

**Pull request merged**
