### PR TITLE
TVR-5204 Update Documentation

### PR DESCRIPTION
**Pull request by patriciadesouza**
Related to TVR-5164 Auto-select agency proposal & ticketIssued updating customAttributes elements which are  used to autoselect the agency proposal.

### CODE REVIEW

**Comment by patriciadesouza** [comment]
Have to close this one because there is another fix made in a more recent commit.

**Comment by patriciadesouza** [comment]
Add new changes to the pull request

**Comment by henryyamamoto-concur** [comment]
@dmclaughlin-concur Can you or someone on the team take a look at this pull request? It's from someone in SAP Germany, but I'm not sure if you folks are aware of it.

**Comment by patriciadesouza** [comment]
The suggested changes made by Sylvain had been commited.

**Comment by patriciadesouza** [comment]
Update pull request

**Comment by dmclaughlin-concur** [comment]
@patriciadesouza  I would recommend updating the sample agency xml as well on the page to show the additional fields.  On the table of custom attributes, see attached with highlights for my edits.
[CustomAttributesElements.docx](https://github.com/concur/developer.concur.com/files/64399/CustomAttributesElements.docx)

**Pull request merged**
