### PR TITLE
Purchase Request RN

### PR DESCRIPTION
**Pull request by sarraloew**

### CODE REVIEW

**Review by charlieconcur — CHANGES_REQUESTED** [review]
2018-11-all.md should be a full date timestamp. I'm also noticing 2018-10-platform.md which should be renamed to a full date timestamp.

**Comment by sarraloew** [comment]
Ok I think it's ready. :shipit:

**Comment by RoAnnC1** [comment]
:shipit:

**Comment by charlieconcur** [comment]
One last item to make sure we bring everything up to date: `src/tools-support/release-notes/api/2018-10-map-example.png` -- should be renamed to include the full date stamp: `2018-10-01-map-example.png`. You will have to update the link to it in `src/tools-support/release-notes/api/2018-10-01.md` as well.

**Review by charlieconcur — APPROVED** [review]

**Pull request merged**
