### PR TITLE
Update Entries.markdown

### PR DESCRIPTION
**Pull request by jimandersen**
Entries
	• PUT Expense entries
		○ Data at the root level is invalid - need expense entry data to use
	• DELETE Expense entries
		○ Need resource with the specified ID
	• GET Expense Entries by ID
		○ Need a resource with a specified resource
	• PUT Expense Entries by ID
	• Requires valid data at the root level: expense entry ID and data to configure the Model Schema

### CODE REVIEW

**Comment by jimandersen** [comment]
That is from the original file structure. I assume it supports the "try it out" function on each of the pages.  I left it there because I thought you would want to include a swagger test opportunity. I can scrape it out of the rest as I go along if you want.

**Comment by henryyamamoto-concur** [comment]
It's not rendering correctly in preview.

**Comment by jimandersen** [comment]
I haven't touched it other than to allow it to push down when I added more content. Are you saying the pull request is not rendering correctly or the swagger/api-explorer isn't?

**Comment by henryyamamoto-concur** [comment]
Wrong page. Should be the same page in api-reference.

**Pull request closed without merging**
